language: go

go:
  - 1.13.x

env:
  - GO111MODULE=on

before_script:
  - make clean
  - go mod download

script:
  - make

after_success:
  - mv out/cover.out coverage.txt
  - bash <(curl -s https://codecov.io/bash)
